const ERROR_CODE = 400;
const UNAUTHORIZED_ERROR = 401;
const NOT_FOUND_ERROR = 404;
const CONFLICTING_REQUEST_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  INTERNAL_SERVER_ERROR,
  ERROR_CODE,
  NOT_FOUND_ERROR,
  CONFLICTING_REQUEST_ERROR,
  UNAUTHORIZED_ERROR,
};
